version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - ginkgolinter
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nestif
    - noctx
    - staticcheck
    - unused
  settings:
    gocyclo:
      min-complexity: 22
    lll:
      line-length: 140
    misspell:
      locale: US
    nestif:
      min-complexity: 12
    staticcheck:
      # TODO: fix static check issues. Contributions are welcome!
      checks:
        - all
        - '-ST1003' # Poorly chosen identifier: https://staticcheck.dev/docs/checks/#ST1003
        - '-ST1005' # Incorrectly formatted error string: https://staticcheck.dev/docs/checks/#ST1005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: //
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
